### ISSUE TITLE
Hangs on install

### ISSUE THREAD

**Issue by marctew** [superleeyom/Hackintosh-Dell-OptiPlex-3050-OpenCore#1]
Trying to install Big Sur (Latest) using your EFI folder and it just hangs on the Apple Logo with a blank progress bar. Any ideas?

**Comment by superleeyom** [comment]
I only tried the version of macOS Big Sur 11.0.1, maybe the latest version is not applicable, you may be able to upgrade the version number of OC.
![image](https://user-images.githubusercontent.com/22115219/113800990-881fd280-978a-11eb-9620-e9d2705778c9.png)
